name: 'action-json-file-to-env'
author: 'hocgin'
description: '.json file to env variable'
inputs:
  debug:
    required: false
    description: 'debug mode'
#outputs:
runs:
  using: node16
  main: dist/index.js
